[package]
name = "pig"
version = "0.2.0"
authors = ["Cbedford"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
